name: fluttercore
description: A new Flutter project.
publish_to: none
version: '1.0.0+1'
environment: 
  sdk: '>=2.19.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: '^1.0.2'
  flutter_localizations: 
    sdk: flutter
  json_annotation: '^4.8.1'
  equatable: '^2.0.3'
  retrofit: '^3.0.1+1'
  injectable: ^2.3.0
  get_it: '^7.2.0'
  dartz: '^0.10.1'
  dio: '^4.0.6'
  google_fonts: ^5.1.0
  dio_logging_interceptor: '^1.0.1'
  flutter_secure_storage: ^9.0.0
  event_bus: '^2.0.0'
  flutter_bloc: '^8.1.1'
  path_provider: '^2.0.11'
  infinite_scroll_pagination: ^4.0.0
  rxdart: '^0.27.5'
  bloc_concurrency: '^0.2.0'
  image_picker: ^1.0.4
  permission_handler: ^11.0.0
  flutter_image_compress: ^2.0.4
  uuid: ^4.0.0
  flutter_local_notifications: ^15.1.1
  go_router: ^10.1.2
  copy_with_extension: ^5.0.4
  change_app_package_name: ^1.1.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: '^2.0.0'
  build_runner: 
  json_serializable: 
  retrofit_generator: 
  injectable_generator: 
  flutter_gen_runner: 
  copy_with_extension_gen: ^5.0.4
flutter: 
  uses-material-design: true
  generate: true
  assets: 
    - assets/images/
    - assets/maps/
